<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlquilerRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class AlquilerRepository extends EntityRepository
{
    public function listadoAlquiler()
    {
        return $this->createQueryBuilder('a')
            ->orderBy('a.id')
            ->getQuery()
            ->getResult();
    }

    public function listadoAlquilerCLiente($id)
    {
        return $this->createQueryBuilder('a')
            ->where('a.usuario = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }

}
