<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
    public function listadoUsuarios()
    {
        return $this->createQueryBuilder('u')
            ->orderBy('u.dni', 'ASC')
            ->getQuery()
            ->getResult();
    }

}
